### ISSUE TITLE
Samples?

### ISSUE THREAD

**Issue by till** [CircleCI-Public/cloudfoundry-orb#10]
The samples seem to be gone.

I am looking for more details on the workspace path to be able to re-use artifacts that were created during my test run. Is this always `/tmp`? Or something I need to setup?

**Comment by iynere** [comment]
@till what samples are you referring to ? they are all here:

https://circleci.com/orbs/registry/orb/circleci/cloudfoundry#usage-examples

or, in source code:

https://github.com/CircleCI-Public/cloudfoundry-orb/blob/master/src/%40orb.yml#L6-L95

**Comment by iynere** [comment]
workspaces docs are here:

https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
https://circleci.com/docs/2.0/configuration-reference/#attach_workspace

**Comment by till** [comment]
@iynere I am trying to run multiple commands in one workflow and get the ability to require on them, etc., so I am looking for something like this:

```
jobs:
  deploy_develop:
    docker:
      - image: circleci/buildpack-deps:stable-curl-browsers
    steps:
      - cloudfoundry/push:
            appname: till-symfony-cd
            manifest: ./manifest.yml
            space: foo
            org: bar
  deploy_preproduction:
    docker:
      - image: circleci/buildpack-deps:stable-curl-browsers
    steps:
      - cloudfoundry/push:
            appname: till-symfony-stage
            manifest: ./manifest.yml
            space: foo
            org: bar
```

(This example just contains multiple "push" for simplicity.)

This doesn't work as CircleCI gives me:

```
# Error calling workflow: 'build_app'
# Error calling job: 'deploy_develop'
# Error calling command: 'cloudfoundry/push'
# Unexpected argument(s): org, space
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

Not entirely sure how to assemble it. Hence, was looking for more samples/examples. The link in the readme was/is broken.
